version: "3"
services:
  nginx:
    image: nginx:mainline
#    network_mode: host
    container_name: nginx
    restart: always
    volumes:
        - ./conf.d:/etc/nginx/conf.d/
        - ./code:/usr/share/nginx/html/
    ports:
        - "80:80"
    links:
        - php
  php:
    image: php:7.2-fpm-stretch
    container_name: php
    restart: always
 #   network_mode: host
    ports:
        - "9000:9000"
    volumes:
        - ./code:/usr/share/nginx/html/
